# site information
name: EMILY FUHRMAN
permalink: none

# default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "projects"
      layout: "post"
      #permalink: "/:categories/:year:month/:title"
