# site information
name:             "EF"
description:      "Emily Fuhrman is a data artist based in New York."
keywords:         "data visualization, mapping, columbia, two sigma"
url:              http://emilyfuhrman.co
permalink:        none

# post settings
defaults:
  - scope:
      path:        ''
      type:        posts
    values:
      category:    projects
      layout:      post
      is_post:     true
  - scope:
      path:        ''
      type:        log
    values:
      category:    log
      layout:      log_post

# formatting
kramdown:
  auto_ids:        false

sass:
  style:           compressed

# collections
collections:
  log:
    output:        true
    permalink:     /:collection/:year/:month/:title.html
