# site information
name:             "EF"
description:      "Emily Fuhrman is a data artist based in Brooklyn, New York."
keywords:         "Data Visualization, Columbia, Two Sigma"
url:              http://emilyfuhrman.co
permalink:        none

# post settings
defaults:
  - scope:
      path:        ''
      type:        posts
    values:
      category:    projects
      layout:      post
      is_post:     true
  - scope:
      path:        ''
      type:        flaneuserie
    values:
      category:    flaneuserie
      layout:      post_flaneuserie

# formatting
kramdown:
  auto_ids:        false

sass:
  style:           compressed

# collections
collections:
  flaneuserie:
    output:        true
    permalink:     /:collection/:year/:month/:title.html
