# site information
name:          EMILY FUHRMAN
description:   Emily Fuhrman.
url:           http://y-li.me
permalink:     none

# default settings
defaults:
  -
    scope:
      path:     ''
      type:     posts
    values:
      category: projects
      layout:   post

# formatting
kramdown:
  auto_ids: false

sass:
  style: compressed

# gems
gems:
  - jekyll-sitemap
