# site information
name:          EMILY FUHRMAN
permalink:     none

# default settings
defaults:
  -
    scope:
      path:     ''
      type:     posts
    values:
      category: projects
      layout:   post

# formatting
kramdown:
  auto_ids: false

# gems
gems:
  - jekyll-sitemap
