# site information
name:          "EF"
description:   "Emily Fuhrman"
url:           http://emilyfuhrman.co
permalink:     none

# default settings
defaults:
  -
    scope:
      path:     ''
      type:     posts
    values:
      category: projects
      layout:   post
      is_post:  true

# formatting
kramdown:
  auto_ids: false

sass:
  style: compressed

# gems
gems:
  - jekyll-sitemap
