# site information
name:          "EF"
description:   "Emily Fuhrman is a data artist based in Brooklyn, New York."
keywords:      "Data Visualization, Columbia, Two Sigma"
url:           http://emilyfuhrman.co
permalink:     none

# default settings
defaults:
  -
    scope:
      path:     ''
      type:     posts
    values:
      category: projects
      layout:   post
      is_post:  true

# formatting
kramdown:
  auto_ids: false

sass:
  style: compressed
