# site information
name:             "EF"
description:      "Emily Fuhrman is a data artist based in London, England."
keywords:         "data art, data visualization, mapping, columbia, two sigma"
url:              http://emilyfuhrman.co
permalink:        none

# post settings
defaults:
  - scope:
      path:        ''
      type:        posts
    values:
      category:    projects
      layout:      post
      is_post:     true

# formatting
kramdown:
  auto_ids:        false

sass:
  style:           compressed
