# site information
name:          EMILY FUHRMAN
permalink:     none

# default settings
defaults:
  -
    scope:
      path:     ''
      type:     posts
    values:
      category: projects
      layout:   post

# formatting
kramdown:
  auto_ids: false

# about page datasets
about_data:
  - id:         edu
    show:       true
  - id:         work
    show:       true
  - id:         clients
    show:       true
  - id:         contact
    show:       true
